---

- name: upgrade npm
  become: true
  shell: |
    npm install -g npm@latest


- name: "Copy compiled backend"
  unarchive:
    src: /root/project/backend/backend.tar.gz
    dest: /home/ubuntu/

- name: install dependencies
  ignore_errors: yes
  shell: |
    cd /home/ubuntu/backend
    npm i
    npm run build

- name: "starting the server"
  become: true
  shell: |
    cd ~/backend
    echo TYPEORM_CONNECTION=postgres >> ~/.bashrc
    echo TYPEORM_ENTITIES=./src/modules/domain/**/*.entity.ts >> ~/.bashrc
    echo TYPEORM_HOST=database-2.c0eyxof0kjwt.us-east-1.rds.amazonaws.com >> ~/.bashrc
    echo TYPEORM_PORT = 5432 >> ~/.bashrc
    echo TYPEORM_USERNAME=postgres >> ~/.bashrc
    echo TYPEORM_PASSWORD=sawy4507 >> ~/.bashrc
    echo TYPEORM_DATABASE=postgres >> ~/.bashrc
    echo TYPEORM_MIGRATIONS=./src/migrations/*.ts >> ~/.bashrc
    echo TYPEORM_MIGRATIONS_DIR=./src/migrations >> ~/.bashrc
    ufw allow 3030/tcp
    pm2 stop default
    pm2 start npm -- start
    nmap localhost
    pm2 ls
  register: server_logs

- name: logs of the start server
  debug:
    msg: "{{ server_logs.stdout_lines }}"