---

- name: upgrade npm
  become: true
  shell: |
    npm install -g npm@latest

- name: add env var in bashrc 
  ansible.builtin.blockinfile:
    path: ~/.bashrc
    block: |
      export TYPEORM_CONNECTION=postgres 
      export TYPEORM_ENTITIES=./src/modules/domain/**/*.entity.ts
      export TYPEORM_HOST=database-2.c0eyxof0kjwt.us-east-1.rds.amazonaws.com
      export TYPEORM_PORT=5432 
      export TYPEORM_USERNAME=postgres
      export TYPEORM_PASSWORD=sawy4507
      export TYPEORM_DATABASE=postgres
      export TYPEORM_MIGRATIONS=./src/migrations/*.ts
      export TYPEORM_MIGRATIONS_DIR=./src/migrations


- name: "Copy compiled backend"
  unarchive:
    src: /root/project/backend/backend.tar.gz
    dest: /home/ubuntu/

- name: install dependencies
  ignore_errors: yes
  shell: |
    cd /home/ubuntu/backend
    npm i
    npm run build

- name: "starting the server"
  become: true
  shell: |
    cd ~/backend
    echo "export TYPEORM_CONNECTION=postgres" >> ~/.bashrc
    echo "export TYPEORM_ENTITIES=./src/modules/domain/**/*.entity.ts" >> ~/.bashrc
    echo "export TYPEORM_HOST=database-2.c0eyxof0kjwt.us-east-1.rds.amazonaws.com" >> ~/.bashrc
    echo "export TYPEORM_PORT = 5432" >> ~/.bashrc
    echo "export TYPEORM_USERNAME=postgres" >> ~/.bashrc
    echo "export TYPEORM_PASSWORD=sawy4507" >> ~/.bashrc
    echo "export TYPEORM_DATABASE=postgres" >> ~/.bashrc
    echo "export TYPEORM_MIGRATIONS=./src/migrations/*.ts" >> ~/.bashrc
    echo "export TYPEORM_MIGRATIONS_DIR=./src/migrations" >> ~/.bashrc
    ufw allow 3030/tcp
    pm2 stop default
    pm2 start npm -- start
    nmap localhost
    pm2 ls
  register: server_logs

- name: logs of the start server
  debug:
    msg: "{{ server_logs.stdout_lines }}"