---

- name: upgrade npm
  become: true
  shell: |
    npm install -g npm@latest


- name: "Copy compiled backend"
  unarchive:
    src: /root/project/backend.tar.gz
    dest: /home/ubuntu/

- name: install dependencies
  ignore_errors: yes
  shell: |
    cd /home/ubuntu/backend
    npm i
    npm run build

- name: "starting the server"
  become: true
  shell: |
    cd ~/backend
    ufw allow 3030/tcp
    pm2 stop default
    pm2 start npm -- start
    nmap localhost
  register: server_logs

- name: logs of the start server
  debug:
    msg: "{{ server_logs.stdout_lines }}"