---

- name: upgrade npm
  become: true
  shell: |
    npm install -g npm@latest


- name: "Copy compiled backend"
  unarchive:
    src: /root/project/backend/backend.tar.gz
    dest: /home/ubuntu/

- name: install dependencies
  ignore_errors: yes
  shell: |
    cd /home/ubuntu/backend
    npm i
    npm run build

- name: install dependencies
  ignore_errors: yes
  shell: |
    cd /home/ubuntu/backend
    export TYPEORM_CONNECTION = "{{ lookup('env', 'TYPEORM_CONNECTION')}}"
    export TYPEORM_ENTITIES = "{{ lookup('env', 'TYPEORM_ENTITIES')}}"
    export TYPEORM_HOST = "{{ lookup('env', 'TYPEORM_HOST')}}"
    export TYPEORM_PORT = 5432
    export TYPEORM_USERNAME = "{{ lookup('env', 'TYPEORM_USERNAME')}}"
    export TYPEORM_PASSWORD = "{{ lookup('env', 'TYPEORM_PASSWORD')}}"
    export TYPEORM_DATABASE = "{{ lookup('env', 'TYPEORM_DATABASE')}}"
    export TYPEORM_MIGRATIONS = "{{ lookup('env', 'TYPEORM_MIGRATIONS')}}"
    export TYPEORM_MIGRATIONS_DIR = "{{ lookup('env', 'TYPEORM_MIGRATIONS_DIR')}}"

- name: "starting the server"
  become: true
  shell: |
    cd ~/backend
    ufw allow 3030/tcp
    pm2 stop default
    pm2 start npm -- start
    nmap localhost
    pm2 ls
  register: server_logs

- name: logs of the start server
  debug:
    msg: "{{ server_logs.stdout_lines }}"